<a href="https://colab.research.google.com/github/psallo/python_test/blob/master/%EC%95%99%EC%83%81%EB%B8%94_%EB%B6%84%EC%84%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import fetch_openml
import pandas as pd

titanic = fetch_openml('titanic', version=1, as_frame=True)

In [2]:
print(titanic)

{'data':       pclass                                             name     sex  \
 0          1                    Allen, Miss. Elisabeth Walton  female
 1          1                   Allison, Master. Hudson Trevor    male
 2          1                     Allison, Miss. Helen Loraine  female
 3          1             Allison, Mr. Hudson Joshua Creighton    male
 4          1  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female
 ...      ...                                              ...     ...
 1304       3                             Zabour, Miss. Hileni  female
 1305       3                            Zabour, Miss. Thamine  female
 1306       3                        Zakarian, Mr. Mapriededer    male
 1307       3                              Zakarian, Mr. Ortin    male
 1308       3                               Zimmerman, Mr. Leo    male

           age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
 0     29.0000      0      0   24160  211.3375       B5        S    2    NaN
 1      0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN
 2      2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN
 3     30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0
 4     25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN
 ...       ...    ...    ...     ...       ...      ...      ...  ...    ...
 1304  14.5000      1      0    2665   14.4542      NaN        C  NaN  328.0
 1305      NaN      1      0    2665   14.4542      NaN        C  NaN    NaN
 1306  26.5000      0      0    2656    7.2250      NaN        C  NaN  304.0
 1307  27.0000      0      0    2670    7.2250      NaN        C  NaN    NaN
 1308  29.0000      0      0  315082    7.8750      NaN        S  NaN    NaN

                             home.dest
 0                        St Louis, MO
 1     Montreal, PQ / Chesterville, ON
 2     Montreal, PQ / Chesterville, ON
 3     Montreal, PQ / Chesterville, ON
 4     Montreal, PQ / Chesterville, ON
 ...                               ...
 1304                              NaN
 1305                              NaN
 1306                              NaN
 1307                              NaN
 1308                              NaN

 [1309 rows x 13 columns],
 'target': 0       1
 1       1
 2       0
 3       0
 4       0
        ..
 1304    0
 1305    0
 1306    0
 1307    0
 1308    0
 Name: survived, Length: 1309, dtype: category
 Categories (2, object): ['0', '1'],
 'frame':       pclass survived                                             name  \
 0          1        1                    Allen, Miss. Elisabeth Walton
 1          1        1                   Allison, Master. Hudson Trevor
 2          1        0                     Allison, Miss. Helen Loraine
 3          1        0             Allison, Mr. Hudson Joshua Creighton
 4          1        0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
 ...      ...      ...                                              ...
 1304       3        0                             Zabour, Miss. Hileni
 1305       3        0                            Zabour, Miss. Thamine
 1306       3        0                        Zakarian, Mr. Mapriededer
 1307       3        0                              Zakarian, Mr. Ortin
 1308       3        0                               Zimmerman, Mr. Leo

          sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
 0     female  29.0000      0      0   24160  211.3375       B5        S    2
 1       male   0.9167      1      2  113781  151.5500  C22 C26        S   11
 2     female   2.0000      1      2  113781  151.5500  C22 C26        S  NaN
 3       male  30.0000      1      2  113781  151.5500  C22 C26        S  NaN
 4     female  25.0000      1      2  113781  151.5500  C22 C26        S  NaN
 ...      ...      ...    ...    ...     ...       ...      ...      ...  ...
 1304  female  14.5000      1      0    2665   14.4542      NaN        C  NaN
 1305  female      NaN      1      0    2665   14.4542      NaN        C  NaN
 1306    male  26.5000      0      0    2656    7.2250      NaN        C  NaN
 1307    male  27.0000      0      0    2670    7.2250      NaN        C  NaN
 1308    male  29.0000      0      0  315082    7.8750      NaN        S  NaN

        body                        home.dest
 0       NaN                     St Louis, MO
 1       NaN  Montreal, PQ / Chesterville, ON
 2       NaN  Montreal, PQ / Chesterville, ON
 3     135.0  Montreal, PQ / Chesterville, ON
 4       NaN  Montreal, PQ / Chesterville, ON
 ...     ...                              ...
 1304  328.0                              NaN
 1305    NaN                              NaN
 1306  304.0                              NaN
 1307    NaN                              NaN
 1308    NaN                              NaN

 [1309 rows x 14 columns],
 'categories': None,
 'feature_names': ['pclass',
  'name',
  'sex',
  'age',
  'sibsp',
  'parch',
  'ticket',
  'fare',
  'cabin',
  'embarked',
  'boat',
  'body',
  'home.dest'],
 'target_names': ['survived'],
 'DESCR': '**Author**: Frank E. Harrell Jr., Thomas Cason  \n**Source**: [Vanderbilt Biostatistics](http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic.html)  \n**Please cite**:   \n\nThe original Titanic dataset, describing the survival status of individual passengers on the Titanic. The titanic data does not contain information from the crew, but it does contain actual ages of half of the passengers. The principal source for data about Titanic passengers is the Encyclopedia Titanica. The datasets used here were begun by a variety of researchers. One of the original sources is Eaton & Haas (1994) Titanic: Triumph and Tragedy, Patrick Stephens Ltd, which includes a passenger list created by many researchers and edited by Michael A. Findlay.\n\nThomas Cason of UVa has greatly updated and improved the titanic data frame using the Encyclopedia Titanica and created the dataset here. Some duplicate passengers have been dropped, many errors corrected, many missing ages filled in, and new variables created. \n\nFor more information about how this dataset was constructed:\nhttp://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3info.txt\n\n\n### Attribute information  \n\nThe variables on our extracted dataset are pclass, survived, name, age, embarked, home.dest, room, ticket, boat, and sex. pclass refers to passenger class (1st, 2nd, 3rd), and is a proxy for socio-economic class. Age is in years, and some infants had fractional values. The titanic2 data frame has no missing data and includes records for the crew, but age is dichotomized at adult vs. child. These data were obtained from Robert Dawson, Saint Mary\'s University, E-mail. The variables are pclass, age, sex, survived. These data frames are useful for demonstrating many of the functions in Hmisc as well as demonstrating binary logistic regression analysis using the Design library. For more details and references see Simonoff, Jeffrey S (1997): The "unusual episode" and a second statistics course. J Statistics Education, Vol. 5 No. 1.\n\nDownloaded from openml.org.',
 'details': {'id': '40945',
  'name': 'Titanic',
  'version': '1',
  'description_version': '10',
  'format': 'ARFF',
  'upload_date': '2017-10-16T01:17:36',
  'licence': 'Public',
  'url': 'https://api.openml.org/data/v1/download/16826755/Titanic.arff',
  'parquet_url': 'https://data.openml.org/datasets/0004/40945/dataset_40945.pq',
  'file_id': '16826755',
  'default_target_attribute': 'survived',
  'tag': ['Data Science', 'History', 'Statistics', 'text_data'],
  'visibility': 'public',
  'minio_url': 'https://data.openml.org/datasets/0004/40945/dataset_40945.pq',
  'status': 'active',
  'processing_date': '2018-10-04 07:19:36',
  'md5_checksum': '60ac7205eee0ba5045c90b3bba95b1c4'},
 'url': 'https://www.openml.org/d/40945'}

In [3]:
type(titanic)

sklearn.utils._bunch.Bunch

In [4]:
df = titanic.frame[['pclass', 'sex', 'age', 'fare', 'survived']].dropna()
df

      pclass     sex      age      fare survived
0          1  female  29.0000  211.3375        1
1          1    male   0.9167  151.5500        1
2          1  female   2.0000  151.5500        0
3          1    male  30.0000  151.5500        0
4          1  female  25.0000  151.5500        0
...      ...     ...      ...       ...      ...
1301       3    male  45.5000    7.2250        0
1304       3  female  14.5000   14.4542        0
1306       3    male  26.5000    7.2250        0
1307       3    male  27.0000    7.2250        0
1308       3    male  29.0000    7.8750        0

[1045 rows x 5 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1045 entries, 0 to 1308
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    1045 non-null   int64
 1   sex       1045 non-null   category
 2   age       1045 non-null   float64
 3   fare      1045 non-null   float64
 4   survived  1045 non-null   category
dtypes: category(2), float64(2), int64(1)
memory usage: 34.9 KB

In [6]:
df['sex'] = df['sex'].map({'male':0, 'female':1})

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1045 entries, 0 to 1308
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    1045 non-null   int64
 1   sex       1045 non-null   category
 2   age       1045 non-null   float64
 3   fare      1045 non-null   float64
 4   survived  1045 non-null   category
dtypes: category(2), float64(2), int64(1)
memory usage: 34.9 KB

In [8]:
df

      pclass sex      age      fare survived
0          1   1  29.0000  211.3375        1
1          1   0   0.9167  151.5500        1
2          1   1   2.0000  151.5500        0
3          1   0  30.0000  151.5500        0
4          1   1  25.0000  151.5500        0
...      ...  ..      ...       ...      ...
1301       3   0  45.5000    7.2250        0
1304       3   1  14.5000   14.4542        0
1306       3   0  26.5000    7.2250        0
1307       3   0  27.0000    7.2250        0
1308       3   0  29.0000    7.8750        0

[1045 rows x 5 columns]

In [9]:
X = df[['pclass', 'sex', 'age', 'fare']]
y = df['survived']

In [10]:
print(X.shape)
print(y.shape)

(1045, 4)
(1045,)

In [12]:
from sklearn.ensemble import StackingClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [15]:
base_models = [
    ('lr', LogisticRegression()),
    ('dt', DecisionTreeClassifier()),
    ('svm', SVC())
]

stack = StackingClassifier(
    estimators=base_models,
    final_estimator=GradientBoostingClassifier()
)

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

stack.fit(X_train, y_train)

pred = stack.predict(X_test)
print("Accuracy:", accuracy_score(y_test, pred))

Accuracy: 0.8038277511961722

In [17]:
from sklearn.datasets import fetch_openml
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# 1) 데이터 준비
titanic = fetch_openml('titanic', version=1, as_frame=True)
df = titanic.frame[['pclass', 'sex', 'age', 'fare', 'survived']].dropna()
df['sex'] = df['sex'].map({'male':0, 'female':1})

X = df[['pclass', 'sex', 'age', 'fare']]
y = df['survived']

# 2) 학습/테스트 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# 3) 랜덤포레스트 모델
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

# 4) 예측 + 정확도
pred = rf.predict(X_test)
print("Accuracy:", accuracy_score(y_test, pred))

Accuracy: 0.7799043062200957